### ISSUE TITLE
Broken links in odata-mock and openapi-mock Readme.md

### ISSUE THREAD

**Issue by arifC** [kyma-incubator/varkes#120]
The links to **"EDMX_MODEL_SPECIFICATION.xml"** don't work anymore since the file `/odata-mock-app/EDMX_MODEL_SPECIFICATION.xml` doesn't exist.

**Comment by a-thaler** [comment]
The readme needs to be re-worked fully, the lower section is not up-to-date at all

**Comment by arifC** [comment]
This seems to be fixed.
