### ISSUE TITLE
app-connector-client: validation of event apis

### ISSUE THREAD

**Issue by a-thaler** [kyma-incubator/varkes#121]
At startup of the app the configured event api specification files should be validated so that you can be sure to not made a mistake in the files.

- Introduce a library to validate asyncapi specs
- Use the library at startup to validate the configured event apis
- let the app not startup in case of validation problems
- Print the validation error in a readable way

**Comment by atakanyenel** [comment]
https://www.npmjs.com/package/yaml-validator 
We can use this package and define our structure in it.

**Comment by a-thaler** [comment]
It is not our format, we are using an official specification called asyncapi and we should use a validator which is specialized on validating that documents. There is indeed one project: https://github.com/Mermade/check_api

**Comment by obadrawi** [comment]
Solved by using check-api npm module for validation
