### ISSUE TITLE
New example with a lot of APIs to stress test kyma

### ISSUE THREAD

**Issue by a-thaler** [kyma-incubator/varkes#136]
There will be real applications having an API granularity which leads to APIS with a number of 300.
To easily test such scenario with Kyma, we need a new examplecovering that.

So please have a new example which has one odata and one openapi definition and generate at startup a varkes_config with 300 entries of them.

**Comment by obadrawi** [comment]
Created stress-mock in examples which is a combined mock of the three modules (app-connector-client, openapi-mock and odata-mock) and generates a config file containing 150 openapi apis , 150 odata apis and 10 events
