### ISSUE TITLE
Show logo in UI and make it overwritable

### ISSUE THREAD

**Issue by a-thaler** [kyma-incubator/varkes#147]
There is a new logo for varkes as svg, please add it to the blue banner in the UI (just in front of the application name). Probably the banner should get lighter from the coloring.

Furthermore, introduce a new config option for a mock to specify a logo which will be then used instead of the default one.
Add a sample logo to the examples.

**Comment by obadrawi** [comment]
Now the varkes logo appears beside the title and it could be overwritten by specifying image logo in the varkes_config file
