### ISSUE TITLE
Support basic authentication for APIs & assure validation

### ISSUE THREAD

**Issue by a-thaler** [kyma-incubator/varkes#153]
Besides OAUth2 we need to support basic auth as well.
So introduce an attribute like "auth":"none|basic|oauth2" and then register either client secrets or basic auth secrets for the API or no secrets at all.
Furthermore, assure that the mocks are respecting that setting and validate the hardcoded secrets at API requests

**Comment by a-thaler** [comment]
The credentials section should look like this:
```
        "credentials": {
            "basic": {
    			"username": "admin",
    			"password": "nimda"
    		}
        },
```

**Comment by obadrawi** [comment]
added "auth" element to apis in config that has one of three values : ["oauth" , "basic", "none"]
