### ISSUE TITLE
Extract management UI into a separate module

### ISSUE THREAD

**Issue by a-thaler** [kyma-incubator/varkes#162]
The UI part of the app-connector-client is fully decoupled from the rest as it is a single page UI based on API calls.
So it should be bundled into a separate module which can be installed optional.
The activation from usage perspective should be similar as for the other modules by just adding it as an express middleware to your express application.
The module might be named "cockpit"

**Comment by obadrawi** [comment]
we created the cockpit module which contains only UI components and uses app-connector to connect to kyma
