### ISSUE TITLE
Extract configuration logic into separate module

### ISSUE THREAD

**Issue by a-thaler** [kyma-incubator/varkes#163]
At the moment every module is doing configuration validation. With that every module is doing it slightly different, no re-usable functions usable. Furthermore, every module supports different features in the configuration and there is no central place defining the syntax.
Also we want to support configuration generation out of a api-spec or a api-folder (like auto-discovery). That logic needs a home.

Extract the configuration logic into a separate module called "@varkes/config" which is required by all modules.
That module will offer that interface methods
- "resolve" - to load a config from file
  - resolves all api specs defined in the config file to an absolute path
  - supports specs by URL
  - validates the config
- "generate" - generates a config based on given specs
  - takes a spec and generates a config
- "discover" - discovers specs from a folder and generates a config
  - takes a folder path and discovers all specs in that folder
  - for every spec it generates a config entry based on the spec type

**Comment by atakanyenel** [comment]
An addition to this idea : It's also possible to extract the logging functionality as every module has the same `logger.ts` file. This file can be moved to newly created ( #240 ) config-validator module, and it can be named as `utils`. Every module can initialise the logging function with their name and expose it for internal usage around module files.

An example of this usage can be seen in the the branch https://github.com/kyma-incubator/varkes/tree/unify-logger

**Comment by a-thaler** [comment]
Thanks for the PR, looks really promising. As the new module is doing much more then validation, let's rename it to "configuration", then also the logging can be part of it
