### ISSUE TITLE
Sending incorrect event-type

### ISSUE THREAD

**Issue by sayanh** [kyma-incubator/varkes#193]
Turns out, Varkes is sending an incorrect event-type while sending an event. It adds the version to the event-type.

E.g.
The request payload was:
```
{
  "event-type": "order.created.v1",
  "event-type-version": "v1",
  "event-time": "2019-04-24T12:41:58.339Z",
  "data": "{\n\t\"orderCode\": \"76272727\"\n}"
}
```

But the event-type should have been: `"event-type": "order.created"`

<img width="1281" alt="Screen Shot 2019-04-24 at 14 44 04" src="https://user-images.githubusercontent.com/5954057/56660377-b42a1200-669f-11e9-8433-b7097d0311e7.png">

**Comment by obadrawi** [comment]
solved this problem in #195
