### ISSUE TITLE
Sort the list of events in the dropdown alphabetically 

### ISSUE THREAD

**Issue by tricky42** [kyma-incubator/varkes#211]
<img width="1464" alt="git_varkes" src="https://user-images.githubusercontent.com/402282/57194178-b139e780-6f11-11e9-8103-8f3c1c02d86c.png">
It would be very helpful if the events in the dropdown of the Remote API View for Async would be sorted alphabetically (e.g. from the SAP Commerce Cloud - Events package).

Other improvement ideas (but less important for now): 
* grouping the events visually by entity e.g.

cart
   cart.created
   cart.saved
   ....
order
   order.created
   order.processing
   ...

**Comment by a-thaler** [comment]
Btw: the combo-box will auto-complete when you start typing in the related text-box, are you aware of that? If not, we need to improve the layout so that people find it intuitive.

**Comment by a-thaler** [comment]
Sorting added. The grouping will be more complicated as the topic naming convention differs per application, so it will involve a lot of assumptions..
