### ISSUE TITLE
event data property contains a json string but should be an object

### ISSUE THREAD

**Issue by jcawley5** [kyma-incubator/varkes#214]
When sending an order created event from commerce mock that data property contains a json string.  Real commerce system send this as an object.
{
  "event-type": "order.created",
  "event-type-version": "v1",
  "event-time": "2019-05-06T20:08:42.713Z",
  "data": "{\n\t\"orderCode\": \"567533336733\"\n}"
}

**Comment by a-thaler** [comment]
Hi Jamie,
thanks for the feedback, we will fix it today.

**Comment by a-thaler** [comment]
fixed, release 0.5.3 is on it's way
