### ISSUE TITLE
Improve error handling when trying to register APIs for an App which doesnt exist anymore.

### ISSUE THREAD

**Issue by tricky42** [kyma-incubator/varkes#241]
**Description**
Trying to register an API / all APIs in Varkes if the Application which was used to "connect" Varkes has been delete leads to a 500 (register all APIs) / 503 (register 1 API) error with a generic error message. And yes, I understand, this is not the most critical error but we need to do proper error handling and have meaningful error messages.

See attached screenshots.
<img width="979" alt="Screen Shot 2019-09-12 at 09 29 05" src="https://user-images.githubusercontent.com/402282/64763306-003afd80-d540-11e9-8d6b-91b2cdcff47a.png">
<img width="981" alt="Screen Shot 2019-09-12 at 09 29 18" src="https://user-images.githubusercontent.com/402282/64763307-003afd80-d540-11e9-96d5-4511c7454afd.png">

<img width="539" alt="Screen Shot 2019-09-12 at 09 33 25" src="https://user-images.githubusercontent.com/402282/64763865-2ca34980-d541-11e9-975e-f53953b89908.png">
<img width="480" alt="Screen Shot 2019-09-12 at 09 33 37" src="https://user-images.githubusercontent.com/402282/64763866-2ca34980-d541-11e9-8640-3a8e29b24168.png">

**Expected Result**
Meaningful error message helping the user to understand what went wrong. I didnt look into the details, but I assume the endpoint which Varkes tries to call does not exist after the App has been deleted and therefore we might get a 404 error from Kyma. Varkes should then present a error message stating that the Application for which we wanted to register API(s) does not exist and it might have been deleted. 

**Workaround**
Spending time to understand, what actual caused the problem.

**Comment by a-thaler** [comment]
I improved the error handling overall and fixed that issue.
