### ISSUE TITLE
on localhost should the entities have results ?

### ISSUE THREAD

**Issue by radu103** [kyma-incubator/varkes#281]
How can the data be mocked with static json files for diff types of requests or automatic based on edmx model ?
there is no description in the readme for @varkes/odata-mock
At this moment, after clone the results are empty arrays

**Comment by a-thaler** [comment]
By default the odata-mock does not startup with data and it will not create fake response data derived from something. So the arrays will be just empty. The mock will keep created data in-memory, so after a POST the GET will return the data.

You can enable persistence to files by setting the persistence option in the config file: https://github.com/kyma-incubator/varkes/blob/c74dce18550ae738ad050d4c75bbdf74b164bd89/modules/configuration/src/types.ts#L30

Having that, json files will be created dynamically in the /data folder which can be used also for the startup to have initial data.

As I'm unhappy with the current odata-mock (very limited feature set from odata spec perspective) I like to avoid writing documentation but instead work on a better mock version first.

**Comment by radu103** [comment]
Ok, Thanks !
