### ISSUE TITLE
Need to implement the certificate renewal strategy

### ISSUE THREAD

**Issue by jcawley5** [kyma-incubator/varkes#286]
Current there is no procedure handling the renewal of an expired certificate. The connection can not be reestablished unless a new connection token is provided.

**Comment by pbochynski** [comment]
Varkes is used mainly in development mode. Can't you just reconnect?

**Comment by jcawley5** [comment]
Currently when using with SKR you do not have an option to generate another token in the CMP, so it requires you to create a new system to obtain one.

**Comment by jcawley5** [comment]
For rest based connections....

https://github.com/kyma-incubator/varkes/pull/287
