### ISSUE TITLE
OpenAPIMock/ODataMock: Change approach of usage

### ISSUE THREAD

**Issue by a-thaler** [kyma-incubator/varkes#58]
As discussed we should change the approach of having the OpenAPI-Mock and the OData-Mock as a regular node module to be usable in a custom application in an easy way.

Adjust the related example to have a basic node application setup, using the module with a custom swagger and customizing it with responses

**Comment by obadrawi** [comment]
waiting on approval for how are we going to publish to npm

**Comment by a-thaler** [comment]
done
