### ISSUE TITLE
Fix npm-publish in prow pipeline

### ISSUE THREAD

**Issue by obadrawi** [kyma-incubator/varkes#86]
Currently varkes is getting build by prow. Here a private account gets used for publishing, please switch to the kyma account.

Furthermore find a way to not fail if version is not getting increased.

See also https://github.com/kyma-project/console/blob/master/scripts/publish-react-components.sh as example

**Comment by a-thaler** [comment]
Proper release process is implemented, see also https://github.com/kyma-incubator/varkes/blob/master/Release.md
