### ISSUE TITLE
Proper Dockerfile for all projects

### ISSUE THREAD

**Issue by a-thaler** [kyma-incubator/varkes#93]
Assure that all Dockerfiles are using fixed base images and have packages up-to-date, see also https://github.com/kyma-project/community/blob/master/guidelines/docker-images.md

Use multi-stage Dockerfiles to ensure that only production relevant files and dependencies are included in the image to keep the footprint small.

**Comment by atakanyenel** [comment]
This guideline assumes that backend is always in Go, and frontend always in JS. Thus nginx image can be used with javascript projects. For this project, we need an image with nodeJS interpreter , and I propose `node:alpine`, which is already being used by the project.
